//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MD.Net.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MD.Net.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file: ..\..\..\Media\Track 001.wav
        /// Channels: 2
        /// SampleRate: 44100
        /// TotalSamples: 007BFAA8
        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  0% done        ///|  0% done        ////  0% done        ///-  0% done        ///\  1% done        ///|  1% done        ////  1% done        ///-  1% done        ///\  1% done        ///|  1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Convert_Atrac {
            get {
                return ResourceManager.GetString("Convert_Atrac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OMA_ATRAC_LP2 {
            get {
                object obj = ResourceManager.GetObject("OMA_ATRAC_LP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] OMA_ATRAC_LP4 {
            get {
                object obj = ResourceManager.GetObject("OMA_ATRAC_LP4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio file size : 53785560 bytes
        ///supported audio file detected
        ///data chunk position at 36
        ///audio data size read from file :           53745552 bytes
        ///audio data size calculated from file size: 53785516 bytes
        ///netmd_acquire_dev: No error
        ///netmd_secure_leave_session : No error
        ///netmd_secure_set_track_protection : No error
        ///netmd_secure_enter_session : No error
        ///netmd_secure_send_key_data : No error
        ///netmd_secure_session_key_exchange : No error
        ///netmd_secure_setup_download : No error
        ///generating packet 1 : 10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Send_SP {
            get {
                return ResourceManager.GetString("Send_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;device&quot;:&quot;Sony MDS-JE780\/JB980&quot;,
        ///  &quot;title&quot;:&quot;Evanescence&quot;,
        ///  &quot;recordedTime&quot;:&quot;00:47:20.09&quot;,
        ///  &quot;totalTime&quot;:&quot;01:14:59.42&quot;,
        ///  &quot;availableTime&quot;:&quot;00:27:26.82&quot;,
        ///  &quot;tracks&quot;:[
        ///    {
        ///      &quot;no&quot;:0,
        ///      &quot;protect&quot;:&quot;UnPROT&quot;,
        ///      &quot;bitrate&quot;:&quot;SP&quot;,
        ///      &quot;time&quot;:&quot;03:41:66&quot;,
        ///      &quot;name&quot;:&quot;What You Want - Evanescence&quot;
        ///    },
        ///    {
        ///      &quot;no&quot;:1,
        ///      &quot;protect&quot;:&quot;UnPROT&quot;,
        ///      &quot;bitrate&quot;:&quot;SP&quot;,
        ///      &quot;time&quot;:&quot;03:33:84&quot;,
        ///      &quot;name&quot;:&quot;Made of Stone - Evanescence&quot;
        ///    },
        ///    {
        ///      &quot;no&quot;:2,
        ///      &quot;protec [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Sony_MDS_JE780___Evanescence {
            get {
                return ResourceManager.GetString("Sony_MDS_JE780___Evanescence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;device&quot;:&quot;Sony MDS-JE780\/JB980&quot;,
        ///  &quot;title&quot;:&quot;&lt;Untitled&gt;&quot;,
        ///  &quot;recordedTime&quot;:&quot;1143:67:00.00&quot;,
        ///  &quot;totalTime&quot;:&quot;80:00:00.00&quot;,
        ///  &quot;availableTime&quot;:&quot;00:11:00.00&quot;,
        ///  &quot;tracks&quot;:[
        ///  ]
        ///}.
        /// </summary>
        internal static string Sony_MDS_JE780___No_Disk {
            get {
                return ResourceManager.GetString("Sony_MDS_JE780___No_Disk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current track: You
        ///Current playback position: 00:00:40.55.
        /// </summary>
        internal static string Status_You {
            get {
                return ResourceManager.GetString("Status_You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_001 {
            get {
                return ResourceManager.GetStream("Track_001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_001_LP2_at3 {
            get {
                return ResourceManager.GetStream("Track_001_LP2_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_001_LP4_at3 {
            get {
                return ResourceManager.GetStream("Track_001_LP4_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_002 {
            get {
                return ResourceManager.GetStream("Track_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_002_LP2_at3 {
            get {
                return ResourceManager.GetStream("Track_002_LP2_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_002_LP4_at3 {
            get {
                return ResourceManager.GetStream("Track_002_LP4_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_003 {
            get {
                return ResourceManager.GetStream("Track_003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_003_LP2_at3 {
            get {
                return ResourceManager.GetStream("Track_003_LP2_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream Track_003_LP4_at3 {
            get {
                return ResourceManager.GetStream("Track_003_LP4_at3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WAV_ATRAC3_LP2 {
            get {
                object obj = ResourceManager.GetObject("WAV_ATRAC3_LP2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] WAV_ATRAC3_LP4 {
            get {
                object obj = ResourceManager.GetObject("WAV_ATRAC3_LP4", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
